FROM kennethadammiller/superset_disasm
ARG testsize=999999
WORKDIR /home/opam/workspace
ENV PATH="/home/opam/.opam/4.05.0/bin:"$PATH

RUN sudo apt-get update && sudo apt-get install libc6-dev-i386 -y

RUN git clone https://github.com/BinaryAnalysisPlatform/x86-binaries.git 
RUN git clone https://github.com/BinaryAnalysisPlatform/x86_64-binaries.git
RUN git clone https://github.com/baumane/capstone.git
RUN git clone https://github.com/KennethAdamMiller/multiverse.git && make -C multiverse
RUN git clone https://github.com/schieb/ELFManip && cd ELFManip && sudo python setup.py install

##### SPEC CPU 2006
COPY ./cpu2006-103.zip ./
RUN unzip cpu2006-103.zip && rm cpu2006-103.zip && rm -rf __MAXOSX result/* && cd cpu2006-103 && $(printf "yes\n") | ./install.sh
COPY Example-linux64-amd64-gcc41.cfg /home/opam/workspace/cpu2006-103/config/
WORKDIR /home/opam/workspace/cpu2006-103
RUN . ./shrc && ./bin/runspec --noreport --config=Example-linux64-amd64-gcc41.cfg --action=run gcc perlbench bzip2 gcc mcf gobmk hmmer sjeng libquantum h264ref omnetpp astar xalancbmk

##### multiverse
RUN sudo pip install --upgrade pip && sudo python -m pip install --upgrade pyelftools==0.24 && sudo pip install pwntools && sudo pip uninstall capstone -y
WORKDIR /home/opam/workspace/capstone
RUN ./make.sh && sudo ./make.sh install && cd bindings/python && sudo python setup.py install
WORKDIR /home/opam/workspace/multiverse
ENV TERM="xterm"
RUN echo "import curses; curses.setupterm();" > x64_asmblr.py && cat x64_assembler.py >> x64_asmblr.py && mv x64_asmblr.py x64_assembler.py
RUN chmod u+x *.sh && ./do_disasm.sh && ./dorewrite.sh && ./copyover.sh #&& ./timerewritten.sh
WORKDIR /home/opam/workspace/superset_disasm

RUN chmod u+x scripts/*
RUN scripts/get_binaries.sh && tail -n $testsize binaries.txt > tmp && mv tmp binaries.txt && scripts/strip_binaries.sh && scripts/run_analyses.sh
RUN git clone https://github.com/KennethAdamMiller/RQ3_binaries.git /home/opam/workspace/rq3_binaries
RUN scripts/rq3.sh > rq3.txt