ARG TAG=master
FROM superset_disasm:$TAG
ARG CACHEBUST

WORKDIR /home/opam/workspace/superset_disasm
RUN make clean ; make ; opam pin add superset_disasm ./ -y --use-internal-solver ;
RUN ./test_superset_disasm.native ; ./functional_tests/test_cmdline.sh ; ./functional_tests/test_run.sh