apiVersion: batch/v1
kind: Job
metadata:
 name: analysis-${TAG}
spec:
  parallelism: ${cores}
  template:
    metadata:
      labels:
        app: analysis-${TAG}
    spec:
     containers:
       - name:  superset-disasm-flambda-${TAG}
         image: ${registry}superset_disasm_flambda:${TAG}
         command: [ "/bin/bash", "scripts/client_analyze.sh", "${TAG}" ]
         volumeMounts:
         - name: x86-64-binaries
           mountPath: /home/opam/workspace/x86_64-binaries
         - name: x86-binaries
           mountPath: /home/opam/workspace/x86-binaries
         - name: arm-binaries
           mountPath: /home/opam/workspace/arm-binaries
     restartPolicy: OnFailure
     volumes:
       - name: x86-64-binaries
         hostPath: 
           path: /Volumes/corpus/x86_64-binaries/
       - name: x86-binaries
         hostPath: 
           path: /Volumes/corpus/x86-binaries/
       - name: arm-binaries
         hostPath: 
           path: /Volumes/corpus/arm-binaries/
 
