apiVersion: batch/v1
kind: Job
metadata:
 name: analysis-${TAG}-${FSUFFIX}
spec:
  parallelism: ${cores}
  template:
    metadata:
      labels:
        app: analysis-${TAG}-${FSUFFIX}
    spec:
     containers:
       - name:  superset-disasm-${TAG}-${FSUFFIX}
         image: ${registry}superset_disasm:${TAG}-${FSUFFIX}
         command: [ "/bin/bash", "scripts/client_analyze.sh", "${TAG}-${FSUFFIX}" ]
         volumeMounts:
         - name: x86-64-binaries
           mountPath: /Volumes/corpus/x86_64-binaries
         - name: x86-binaries
           mountPath: /Volumes/corpus/x86-binaries
         - name: arm-binaries
           mountPath: /Volumes/corpus/arm-binaries
         - name: caches
           mountPath: /home/opam/.cache/bap
     restartPolicy: OnFailure
     volumes:
       - name: x86-64-binaries
         hostPath: 
           path: /Volumes/corpus/x86_64-binaries/
       - name: x86-binaries
         hostPath: 
           path: /Volumes/corpus/x86-binaries/
       - name: arm-binaries
         hostPath: 
           path: /Volumes/corpus/arm-binaries/
       - name: caches
         hostPath:
           path: /Volumes/caches/${TAG}/
 
