apiVersion: v1
kind: Service
metadata:
  name: broker:${TAG}
spec:
  containers:
    - image: superset_disasm_flambda:${TAG}
  ports:
    - name: service
      protocol: TCP
      port: 9999
      targetPort: 9999
    - name: collector
      protocol: TCP
      port: 9998
      targetPort: 9998
    - name: killed
      protocol: TCP
      port: 9997
      targetPort: 9997
