apiVersion: batch/v1
kind: Job
metadata:
  name: broker-${TAG}
spec:
  template:
    metadata:
     name: broker-${TAG}
     labels:
       app: broker-${TAG}
    spec:
     containers:
       - name: superset-disasm-flambda-${TAG}
         image: ${registry}superset_disasm_flambda:${TAG}
         command: [ /bin/bash, /home/opam/workspace/superset_disasm/scripts/run_broker.sh, "${test_size}" ]
         volumeMounts:
           - name: x86-64-binaries
             mountPath: /home/opam/workspace/x86_64-binaries
           - name: x86-binaries
             mountPath: /home/opam/workspace/x86-binaries
           - name: arm-binaries
             mountPath: /home/opam/workspace/arm-binaries
         ports:
           - name: service
             containerPort: 9999
           - name: collector
             containerPort: 9998
           - name: killed
             containerPort: 9997
           - name: cache-transfer
             containerPort: 9996
     restartPolicy: Never
     volumes:
       - name: x86-64-binaries
         hostPath: 
           path: /Volumes/corpus/x86_64-binaries/
       - name: x86-binaries
         hostPath: 
           path: /Volumes/corpus/x86-binaries/
       - name: arm-binaries
         hostPath: 
           path: /Volumes/corpus/arm-binaries/
  
