apiVersion: v1
kind: Pod
metadata:
 name: broker-${TAG}
spec:
 containers:
   - name: superset-disasm-flambda-${TAG}
     image: superset_disasm_flambda:${TAG}
     command: [ "scripts/run_broker.sh" ]
     volumeMounts:
     - name: x86-64-binaries
       mountPath: /home/opam/workspace/x86_64-binaries
     - name: x86-binaries
       mountPath: /home/opam/workspace/x86-binaries
     - name: arm-binaries
       mountPath: /home/opam/workspace/arm-binaries
     ports:
       - name: service
         containerPort: 9999
         hostPort: 9999
       - name: collector
         containerPort: 9998
         hostPort: 9998
       - name: killed
         containerPort: 9997
         hostPort: 9997
       - name: cache-transfer
         containerPort: 9996
         hostPort: 9996
 volumes:
   - name: x86-64-binaries
     hostPath: 
       path: ${HOME}/workspace/x86_64-binaries/
   - name: x86-binaries
     hostPath: 
       path: ${HOME}/workspace/x86-binaries/
   - name: arm-binaries
     hostPath: 
       path: ${HOME}/workspace/arm-binaries/

